version: 2

sources:
  - name: ecommerce_raw
    project: my-project-learning-496207
    dataset: ecommerce_raw
    tables:
      - name: raw_orders
      - name: raw_order_items
      - name: raw_customers
      - name: raw_products
      - name: raw_sellers
      - name: raw_order_payments
      - name: raw_order_reviews
      - name: raw_category_translation